install.packages("palmerpenguins")
install.packages("here")
require(palmerpenguins)
require(here)
library("palmerpenguins")
penguins = data.frame(penguins)
mean(penguins$body_mass_g)
summary(penguins)
boxplot(penguins$bill_length_mm)
boxplot(bill_depth_mm ~ sex, data = penguins)
par(mfrow = c(1, 2))
boxplot(penguins$bill_legnth_mm)
boxplot(bill_length_mm ~ sex, data = penguins)
coplot(body_mass_g ~ flipper_length_mm | island, data = penguins)

require(here)
png(filename = here("basic_coplot.png"), width = 800, height = 600)
coplot(body_mass_g ~ flipper_length_mm | island, data = penguins, rows = 1)
dev.off()